### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by if412010** [leongatys/DeepTextures#5]
Hi Leon,

I am very new for this Caffe thing,
but i want to try to install it on my Ubuntu PC,

What should i do? i have installed the Caffe Framework according to this tutorial: http://caffe.berkeleyvision.org/install_apt.html

so what should i do next?

**Comment by rrshaban** [comment]
If you can successfully `import caffe` in Python, you should be able to follow the code in [Example.ipynb](https://github.com/leongatys/DeepTextures/blob/master/Example.ipynb)

**Comment by if412010** [comment]
i dont really get what you mean by "import caffe in python", i am really new

**Comment by rrshaban** [comment]
@if412010 you might want to start with a beginners Python tutorial; you'll have a hard time understanding the example code otherwise
