### ISSUE TITLE
Array() error

### ISSUE THREAD

**Issue by haeseonii** [leongatys/DeepTextures#8]
Hello,

I am trying to run Example.ipynb. I couldn't get ipython notebook to run, so I exported it to a python script.
When I run, it fails on imagenet_mean = array(...) line saying that
name 'array' is not defined.

I tried importing array (from array import array), but it then fails saying that
TypeError: array() argument 1 or typecode must be char (string or ascii-unicode with length 1), not list

Could you please help? Thanks!
John

**Comment by abdu307** [comment]
can you try using (from numpy import array) instead of (from array import array)

**Comment by haeseonii** [comment]
I just tried it and it works. Thanks so much!
