### ISSUE TITLE
Cannot download the scaled VGG net weights

### ISSUE THREAD

**Issue by wzm2256** [leongatys/DeepTextures#9]
not able to connect to 
bethgelab.org/media/uploads/deeptextures/vgg_normalised.caffemodel

Any other way to download this file?

**Comment by leongatys** [comment]
The link looks fine to me.
Maybe there are some other issues on your side?

Best
Leon

**Comment by endolith** [comment]
> It's not just you! bethgelab.org is down.

https://downforeveryoneorjustme.com/bethgelab.org?proto=https

**Comment by endolith** [comment]
is this the same file? https://github.com/paulu/deepfeatinterp/blob/master/models/VGG_CNN_19/vgg_normalised.caffemodel
